# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "iphone" do
# for networking
pod 'AFNetworking', '~> 2.0.3'
# for log
pod 'CocoaLumberjack', '~> 1.7.0'
# for debug
pod 'PonyDebugger', '~> 0.3.1'
end

target "iphoneTests" do

end

